use_frameworks!

target 'MagiPhotoBrowser_Example' do
    use_frameworks!
  pod 'MagiPhotoBrowser'
  pod 'Kingfisher',             '~> 4.10.0'
  pod 'KingfisherWebP',         '~> 0.4.2'
  pod 'libwebp',                '1.0.0'
  
  target 'MagiPhotoBrowser_Tests' do
    inherit! :search_paths

  end
end
