# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
cache: cocoapods
podfile: ExampleRepo/photoBrowser/Podfile

env:
global:
- LANG=en_US.UTF-8
- LC_ALL=en_US.UTF-8
- XCODE_WORKSPACE=ExampleRepo/ExampleRepo/photoBrowser/photoBrowser.xcworkspace
matrix:
- SCHEME="photoBrowser"

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- pod update --project-directory=ExampleRepo/photoBrowser
- pod install --project-directory=ExampleRepo/photoBrowser
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace ExampleRepo/photoBrowser/photoBrowser.xcworkspace -scheme photoBrowser -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
after_success:
- sleep 3
